version: '3.1'
services:
  ewm-stats:
    build: ewm-stats
    image: ewm-stats
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SERVER_PORT=9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
      - SPRING_DATASOURCE_USERNAME=java_junior
      - SPRING_DATASOURCE_PASSWORD=practicum2021_2022

  stats-db:
    image: postgres:15.1-alpine
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=java_junior
      - POSTGRES_PASSWORD=practicum2021_2022

  ewm-main:
    build: ewm-main
    image: ewm-main
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - ewm-stats
    environment:
      - SERVER_PORT=8080
      - EWM-STATS_URL=http://ewm-stats:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/main
      - SPRING_DATASOURCE_USERNAME=java_junior
      - SPRING_DATASOURCE_PASSWORD=practicum2021_2022

  ewm-db:
    image: postgres:15.1-alpine
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=main
      - POSTGRES_USER=java_junior
      - POSTGRES_PASSWORD=practicum2021_2022